import Testing
@testable import WispCore

struct PrivacyFilterTests {
    // The one and only thing Wisp skips: its own paste echo, marked with the
    // private self-paste type (see Paster.write). Re-recording it would clobber the
    // entry's captured HTML with a text-only copy.
    @Test func ownPasteOutputIsIgnored() {
        #expect(PrivacyFilter.shouldIgnore(types: [PrivacyFilter.selfPasteType.rawValue]))
        #expect(PrivacyFilter.shouldIgnore(
            types: ["public.utf8-plain-text", PrivacyFilter.selfPasteType.rawValue]))
    }

    // Wisp is a *complete* history: everything you copy is recorded, secrets
    // included. None of the markers that used to suppress secrets do so anymore.
    @Test func concealedContentIsRecorded() {
        #expect(!PrivacyFilter.shouldIgnore(
            types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]))
    }

    @Test func transientContentIsRecorded() {
        #expect(!PrivacyFilter.shouldIgnore(types: ["org.nspasteboard.TransientType"]))
    }

    // Third-party auto-generated clips are recorded too. (Wisp stamps this marker on
    // its OWN pastes as a courtesy to other managers, but keys its own skip on the
    // private self-paste type — so a foreign AutoGeneratedType clip still records.)
    @Test func foreignAutoGeneratedContentIsRecorded() {
        #expect(!PrivacyFilter.shouldIgnore(types: ["org.nspasteboard.AutoGeneratedType"]))
    }

    @Test func passwordManagerContentIsRecorded() {
        // Legacy 1Password pasteboard type — no longer a reason to skip.
        #expect(!PrivacyFilter.shouldIgnore(types: ["com.agilebits.onepassword"]))
    }

    @Test func plainTextIsRecorded() {
        #expect(!PrivacyFilter.shouldIgnore(types: ["public.utf8-plain-text"]))
    }

    @Test func emptyTypesAreRecorded() {
        #expect(!PrivacyFilter.shouldIgnore(types: []))
    }
}
