import Testing
@testable import WispCore

struct PrivacyFilterTests {
    @Test func concealedTypeIsIgnored() {
        #expect(PrivacyFilter.shouldIgnore(
            types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"],
            source: nil))
    }

    @Test func transientTypeIsIgnored() {
        #expect(PrivacyFilter.shouldIgnore(
            types: ["org.nspasteboard.TransientType"], source: nil))
    }

    @Test func autoGeneratedTypeIsIgnored() {
        #expect(PrivacyFilter.shouldIgnore(
            types: ["org.nspasteboard.AutoGeneratedType"], source: nil))
    }

    @Test func legacyOnePasswordTypeIsIgnored() {
        #expect(PrivacyFilter.shouldIgnore(
            types: ["com.agilebits.onepassword"], source: nil))
    }

    @Test func plainTextIsRecorded() {
        #expect(!PrivacyFilter.shouldIgnore(
            types: ["public.utf8-plain-text"], source: "com.apple.Safari"))
    }

    @Test func knownSecretSourceIsIgnored() {
        #expect(PrivacyFilter.shouldIgnore(
            types: ["public.utf8-plain-text"], source: "com.bitwarden.desktop"))
    }

    @Test func unknownSourceIsRecorded() {
        #expect(!PrivacyFilter.shouldIgnore(
            types: ["public.utf8-plain-text"], source: "com.example.editor"))
    }
}
