import AppKit

/// Places text on the pasteboard and pastes it into the previously-active app by
/// synthesizing ⌘V. That synthetic keystroke is the *only* reason Wisp asks for
/// Accessibility — and if it's not granted, the text is still on the clipboard
/// so a manual ⌘V works.
@MainActor
enum Paster {
    /// Plain paste (default ⏎): place the text as-is. Exactly the original
    /// behaviour — what you copied is what lands.
    static func paste(_ text: String, into app: NSRunningApplication?) {
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        write(item, into: app)
    }

    /// Formatted paste (⌥⏎): place rich flavors alongside the plain text on a
    /// single pasteboard item. Rich targets (Slack, Notes, Mail…) render the
    /// formatting; plain-text editors (Sublime, Obsidian) still get `text`.
    ///
    /// Two sources of formatting, in order of fidelity:
    ///   • `sourceHTML` — the originating app's own HTML, captured at copy time
    ///     (e.g. select-and-copy from Claude). Re-emitted verbatim for an exact
    ///     reproduction. We deliberately do NOT parse it ourselves: the
    ///     NSAttributedString HTML importer can fetch remote resources, so feeding
    ///     it untrusted HTML would mean a network request. Notes/Slack/Mail read
    ///     HTML directly, so no RTF is needed here.
    ///   • otherwise — synthesize HTML from the entry's Markdown. That HTML is our
    ///     own and references no external resources, so deriving RTF locally is safe.
    static func pasteFormatted(text: String, sourceHTML: String?,
                               into app: NSRunningApplication?) {
        write(formattedItem(text: text, sourceHTML: sourceHTML), into: app)
    }

    /// Stamp the item as Wisp-generated (so our own monitor — and other managers —
    /// don't re-record this paste, which for a plain ⏎ would overwrite the entry's
    /// captured HTML with a text-only copy), put it on the pasteboard, and deliver.
    private static func write(_ item: NSPasteboardItem, into app: NSRunningApplication?) {
        item.setString("", forType: PrivacyFilter.autoGeneratedType)
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.writeObjects([item])
        deliver(to: app)
    }

    /// Build the multi-flavor pasteboard item for a formatted paste. Extracted so
    /// it's testable without actually pasting. Passthrough re-emits `sourceHTML`
    /// unparsed (no RTF); synthesis renders Markdown → HTML and derives RTF.
    static func formattedItem(text: String, sourceHTML: String?) -> NSPasteboardItem {
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)

        if let sourceHTML, !sourceHTML.isEmpty {
            item.setString(sourceHTML, forType: .html) // passthrough, unparsed
        } else {
            let document = "<!DOCTYPE html><html><head><meta charset=\"utf-8\"></head><body>\(MarkdownRenderer.html(from: text))</body></html>"
            item.setString(document, forType: .html)
            if let rtf = rtfData(fromHTML: document) {
                item.setData(rtf, forType: .rtf)
            }
        }
        return item
    }

    /// Return focus to the previous app and synthesize ⌘V (if allowed). Shared by
    /// both paste paths. If Accessibility isn't granted, the clip is on the board
    /// regardless — a manual ⌘V still works.
    private static func deliver(to app: NSRunningApplication?) {
        app?.activate(options: [.activateIgnoringOtherApps])

        guard AccessibilityAuthorizer.isTrusted else {
            // No permission yet: nudge once. The clip is on the board regardless.
            AccessibilityAuthorizer.requestIfNeeded()
            return
        }

        // Let the activation land before we send the keystroke.
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.08) {
            sendCommandV()
        }
    }

    /// Best-effort RTF derived from our *own* (trusted, resource-free) HTML, so
    /// RTF-first targets get formatting too. Returns nil on failure — we then just
    /// ship plain text + HTML. The HTML importer is WebKit-backed and main-thread
    /// only; we're already on the main actor, and our HTML references no external
    /// resources, so there's no network fetch.
    private static func rtfData(fromHTML html: String) -> Data? {
        guard let data = html.data(using: .utf8),
              let attributed = try? NSAttributedString(
                  data: data,
                  options: [.documentType: NSAttributedString.DocumentType.html,
                            .characterEncoding: String.Encoding.utf8.rawValue],
                  documentAttributes: nil)
        else { return nil }
        return try? attributed.data(
            from: NSRange(location: 0, length: attributed.length),
            documentAttributes: [.documentType: NSAttributedString.DocumentType.rtf])
    }

    private static func sendCommandV() {
        let source = CGEventSource(stateID: .combinedSessionState)
        let vKeyCode: CGKeyCode = 0x09 // 'v'
        guard let keyDown = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: true),
              let keyUp = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: false)
        else { return }
        keyDown.flags = .maskCommand
        keyUp.flags = .maskCommand
        keyDown.post(tap: .cghidEventTap)
        keyUp.post(tap: .cghidEventTap)
    }
}
