import AppKit

/// Decides whether a pasteboard change should be recorded.
///
/// Wisp is a *complete* clipboard history: it records everything you copy —
/// usernames, passwords, and one-time codes included. That is deliberate. The
/// safety guarantee is not "Wisp avoids seeing secrets" but "secrets can't
/// escape": the history lives only in RAM (never written to disk), Wisp has no
/// networking code or entitlement, runs under the Hardened Runtime, and its
/// windows are excluded from screen capture. Quit Wisp or reboot and everything
/// it held is gone. The full threat model — including the residual risks Wisp
/// can't eliminate — is in docs/SECURITY.md.
///
/// The one and only thing Wisp skips is its OWN paste output. When you paste an
/// entry, Wisp puts it back on the system pasteboard to deliver it; re-recording
/// that echo would overwrite the entry's captured HTML with a text-only copy (and
/// pointlessly churn the history). Wisp stamps its pastes with a private marker
/// and skips exactly those — nothing else is ever filtered.
enum PrivacyFilter {
    /// Private pasteboard type Wisp stamps on its own paste output (see
    /// `Paster.write`). The monitor skips any clip carrying it, so delivering a
    /// paste never re-records it. This is plumbing — the sole reason
    /// `shouldIgnore` can ever return true — not a privacy policy.
    static let selfPasteType = NSPasteboard.PasteboardType("com.brinas.wisp.self-paste")

    /// The nspasteboard.org "app-generated" marker. Wisp does NOT use it to filter
    /// anything (it records auto-generated clips like any other). It only stamps it
    /// on its own paste output as a courtesy, so *other* well-behaved clipboard
    /// managers running alongside Wisp skip the echo too.
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// The nspasteboard.org "confidential" marker. Wisp does NOT filter on it (it
    /// records concealed clips like any other — that's the whole point now). It only
    /// stamps it on its own paste output as a *stronger* hint to any other clipboard
    /// manager running alongside Wisp not to store the echo. Advisory only: a hostile
    /// or careless app can still read the system pasteboard regardless (see
    /// docs/SECURITY.md → residual risks).
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")

    /// The nspasteboard.org "who put this here" marker. Wisp doesn't filter on it —
    /// it's read only, best-effort, to label an entry with its originating app.
    static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")

    /// Pure, testable core: record everything except Wisp's own paste echo.
    static func shouldIgnore(types: [String]) -> Bool {
        types.contains(selfPasteType.rawValue)
    }

    /// Best-effort source app bundle id (for display), if advertised.
    static func source(of pasteboard: NSPasteboard) -> String? {
        pasteboard.string(forType: sourceType)
    }
}
