import AppKit

/// Decides whether a pasteboard change should be recorded. This is the heart of
/// Wisp's "never remember secrets" promise.
///
/// Reference: https://nspasteboard.org — the de-facto standard for marking
/// transient/concealed clipboard data on macOS. Password managers set these
/// markers so well-behaved clipboard tools skip their contents.
enum PrivacyFilter {
    /// Pasteboard types that explicitly mean "do not record this".
    static let ignoredTypes: Set<String> = [
        // Official nspasteboard.org markers.
        "org.nspasteboard.TransientType",      // momentary (e.g. clipboard rings)
        "org.nspasteboard.ConcealedType",      // passwords / secrets
        "org.nspasteboard.AutoGeneratedType",  // app-generated; user didn't copy it
        // Legacy / proprietary markers still seen in the wild.
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "com.agilebits.onepassword",
        "com.apple.is-remote-clipboard"        // Handoff / Universal Clipboard
    ]

    /// Bundle identifiers of well-known secret managers. Belt-and-suspenders for
    /// the cases where they forget to set a concealed marker.
    static let secretSourceBundleIDs: Set<String> = [
        "com.agilebits.onepassword",
        "com.agilebits.onepassword7",
        "com.1password.1password",
        "com.bitwarden.desktop",
        "com.lastpass.LastPass",
        "com.dashlane.Dashlane",
        "in.sinew.Walletx",              // Enpass
        "org.keepassxc.keepassxc",
        "com.mackieg.MacPass",
        "com.kryptco.kr"
    ]

    static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")

    /// Pure, testable core: decide from a list of present type identifiers and an
    /// optional advertised source bundle id.
    static func shouldIgnore(types: [String], source: String?) -> Bool {
        if types.contains(where: ignoredTypes.contains) {
            return true
        }
        if let source, secretSourceBundleIDs.contains(source) {
            return true
        }
        return false
    }

    /// True when the current pasteboard contents must NOT be recorded.
    static func shouldIgnore(_ pasteboard: NSPasteboard) -> Bool {
        shouldIgnore(types: (pasteboard.types ?? []).map(\.rawValue),
                     source: pasteboard.string(forType: sourceType))
    }

    /// Best-effort source app bundle id (for display), if advertised.
    static func source(of pasteboard: NSPasteboard) -> String? {
        pasteboard.string(forType: sourceType)
    }
}
